# Generated by Django 5.1.5 on 2025-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="year_of_release",
            field=models.CharField(default="Unknown", max_length=4),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
